name: odm2client
channels:
- odm2
- conda-forge
- r
dependencies:
- odm2api
- yodatools
- requests
- folium
- geopandas
- ulmo
- owslib
- scipy
- xarray
- ipykernel
# R-Packages
- r=3.3.2
- r-xml
- r-rjsonio
- r-irkernel
- r-ggplot2
- r-tidyverse
- r-lubridate