name: odm2client
channels:
- odm2
- conda-forge
dependencies:
- odm2api
- yodatools
- requests
- folium
- geopandas
- ulmo
- owslib
- scipy
- xarray
# Jupyter notebook
- ipykernel
- jupyter
- nb_conda_kernels
