name: odm2client
channels:
- odm2
- conda-forge
dependencies:
- python=2.7
- odm2api
- yodatools
- requests
- scipy
- xarray
- folium
- geopandas
- owslib
- ulmo
# Jupyter notebook
- ipykernel
- jupyter
- nb_conda_kernels
