name: renvironment
channels:
- conda-forge
- r
dependencies:
- r=3.3.2
- r-xml
- r-xml2
- r-rgdal
- r-rjsonio
- r-jsonlite
- r-rodbc
- r-httr
- r-rvest
- r-e1071
- r-acepack
- r-hmisc
- r-mvtnorm
- r-igraph
- r-vegan
- r-rcurl
- r-yaml
- r-irkernel
- r-ggplot2
- r-tidyverse
- r-lubridate
- r-devtools
- r-waterml
- r-aqp
- icu=58.*
# Note: packages below needs to be installed manually
# Rcharts ---
# devtools::install_github("ramnathv/rCharts")
# Soil-related Packages ---
# install.packages("dismo", repos="http://cran.us.r-project.org")
# install.packages("rgeos", repos="http://cran.us.r-project.org")
# install.packages("ape", repos="http://cran.us.r-project.org")
# install.packages("circular", repos="http://cran.us.r-project.org")
# devtools::install_github("ncss-tech/soilDB", dependencies=FALSE, upgrade_dependencies=FALSE)
# devtools::install_github("ncss-tech/sharpshootR", dependencies=FALSE, upgrade_dependencies=FALSE)